// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxdqnpwmhcrmjwiabncm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZHFucHdtaGNybWp3aWFibmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTg1NDcsImV4cCI6MjA2NDA3NDU0N30.r-1dc2-hoUc8dmLvO2o_WYgTe-y-9LVAZCNWe3HBrlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);